### PR TITLE
Ansi parser net driver

### PR DESCRIPTION
**Pull request by tznind**
## Fixes

- Fixes #_____

## Proposed Changes/Todos

- [ ] Todo 1

## Pull Request checklist:

- [ ] I've named my PR in the form of "Fixes #issue. Terse description."
- [ ] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [ ] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [ ] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any poor grammar or misspellings
- [ ] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tznind** [comment]
@BDisp what do you think of the changes in this PR? any issues? I think behaviour matches, Theres now some dead code I can remove.

Only issue I have is that the mouse seems to like constantly click while held down.

**Comment by tznind** [comment]
Seems that with this particular terminal I am using the DAR can still interrupt in the middle of a mouse report event.  I believe this is a bug in the terminal environment itself.  I got around it by throttling with WindowsDriver and probably its similar story here.

Mouse events are coming in regularly (blue and purple).  DAR response `<esc>[?1;0c` comes in but is written to the output stream in the middle of reporting a mouse event

image

**Comment by BDisp** [comment]
That seems it's some async response desynchronized. The DAR response is being enqueued before ending read the mouse input. We must ensured that the `ConcurrentQueue` doesn't mixed anything. In the `WindowsDriver` I already realized that the mouse acts as button pressed+mousemove when the mouse was already released after open a scenario. Maybe a `Windows Terminal` issue because that doesn't happens with the `conhost`.

**Comment by tznind** [comment]
Not related to the `ConcurrentQueue`.  It was doing this on WindowsDriver too before I implemented any of that - though in that case the DAR responses were interupting one another not interrupting the mouse.

It is I think in the raw input stream from the console not any of our code.  So it is an issue with the very old terminal I as using.  I do not see this bug in the Windows Terminal or other terminals.

**Comment by tznind** [comment]
@BDisp can you test these changes if you are happy with them I Will merge them into the main ansi-parser branch

**Comment by BDisp** [comment]
You need to ensure that the `_inputReadyCancellationTokenSource` isn't null in the  `DequeueInput` method. Put it in a try/finally block.

image

**Comment by tznind** [comment]
Is this part of shutdown/exit? how do I trigger this? it looks like OperationCancelledException here i.e. the token just got cancelled - maybe it became null as part of dispose as well as cancelled?.

**Comment by BDisp** [comment]
Yes it's when I exit the ANSI scenario to the UICatalog main.

**Comment by tznind** [comment]
Ok got it, did you hit Esc twice? Maybe it just happened when you exit the application?

`_inputReadyCancellationTokenSource` is only ever cancelled in Dispose method of NetEvents.

So I think the code that references it can be simplified a lot by just putting a root level try/catch OperationCancelledException in the Task itself and not set it to null in dispose.

I will investigate

**Comment by BDisp** [comment]
No, just once. Remember that when exit a scenario the UICatalog perform a real Shutdown and Init. The Ansi scenario should dispose any pending request on exit.

**Comment by BDisp** [comment]
You need to change to this:

```cs
    public InputResult? DequeueInput ()
    {
        while (!_netEventsDisposed.Token.IsCancellationRequested)
        {
            try
            {
                _winChange.Set ();

                if (_inputQueue.TryTake (out InputResult? item, -1, _netEventsDisposed.Token))
                {
                    return item;
                }
            }
            catch (OperationCanceledException)
            {
                break;
            }
        }

        return null;
    }

```

**Comment by tznind** [comment]
Ok @BDisp I think this is basically working right so can take it into main ansi parser branch

**Comment by BDisp** [comment]
But it was still throwing an exception on exit from the scenario Ansi.

**Comment by tznind** [comment]
Even after [becca1a](https://github.com/tznind/gui.cs/pull/172/commits/becca1a3a0c08d2487aed55c81ef0f0cc935a8dc) ? is the thrown exception not caught further up? I am not seeing this - do you have 'break on any exception' set?

**Comment by tznind** [comment]
Looks like you have the tick box 'Break when this exception type is user-handled' ticked

**Comment by tznind** [comment]
Hmn actually that says unhandled.... what happens if you step debugger does it go to the catch in the Task?

**Comment by BDisp** [comment]
> Even after [becca1a](https://github.com/tznind/gui.cs/pull/172/commits/becca1a3a0c08d2487aed55c81ef0f0cc935a8dc) ? is the thrown exception not caught further up? I am not seeing this - do you have 'break on any exception' set?

I'm using the current ansi-parser branch and still happen.

> Looks like you have the tick box 'Break when this exception type is user-handled' ticked

Yes I have. I want to ensure if the break wasn't handled.

> Hmn actually that says 'unhandled' - I am miss reading.... what happens if you step debugger does it go to the catch in the Task?

No, it stay always in the same line.

**Comment by BDisp** [comment]
If I untick it continue without throwing the error, but it break again when I enter/exit the scenario. I recommend to add a try/catch block to avoid this.

**Comment by BDisp** [comment]
> If I untick it continue without throwing the error, but it break again when I enter/exit the scenario. I recommend to add a try/catch block to avoid this.

After exit and run again the exception doesn't occur but if I tick again the `OperationCaceledException` it continue. But I still recommend the above addition.

**Comment by tznind** [comment]
Ok I have added in https://github.com/gui-cs/Terminal.Gui/pull/3791/commits/2b7d0c7f70a2afbca1bc24bbde761deee256e5a9

Please ensure this fix your issue? Its now in `ansi-parser` branch as this was merged

**Comment by BDisp** [comment]
> Ok I have added in [gui-cs@2b7d0c7](https://github.com/gui-cs/Terminal.Gui/commit/2b7d0c7f70a2afbca1bc24bbde761deee256e5a9)
> 
> Please ensure this fix your issue? Its now in `ansi-parser` branch as this was merged

Yes it should work because I already had tried that code before. Thanks.

**Pull request merged**
