### PR TITLE
Implementing keybindings in Autocomplete. I had to derive from View.

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
Personally, I don't like this solution I made. `Autocomplete` is very tied to `TextView` and I think this can be used for other views too. My proposal is create a interface `IAutocomplete` and a `AutocompleteBase` with common code. Any view who want to implement `Autocomplete` must create a new class derived from `AutocompleteBase`.
In the case of the `TextView` creating a new class:
```cs
public class TextViewAutocomplete : AutocompleteBase
```
and in the `TextView` declare the property as:
```cs
public IAutocomplete Autocomplete { get; protected set; } = new TextViewAutocomplete ();
```
In this case the `Autocomplete` doesn't need to be derived from `View` and not using the key bindings.
What your opinion?

**Comment by tznind** [comment]
I think that is a better solution yeah :)

**Comment by BDisp** [comment]
Only a question, I think I can use the `Autocomplete` class changing it to `abstract` instead of creating another class `AutocompleteBase`, right?

**Comment by tznind** [comment]
Yes I think that is ok.

**Comment by BDisp** [comment]
I hope you like it. I'll try to implement the Autocomplete to the `TextField`.

**Comment by tznind** [comment]
I'll merge this but I think theres some stuff that can be moved out of `TextViewAutocomplete` up to the base class `Autocomplete` so that it is easier for other views to implement.

**Comment by BDisp** [comment]
> I'll merge this but I think theres some stuff that can be moved out of `TextViewAutocomplete` up to the base class `Autocomplete` so that it is easier for other views to implement.

Yes you are right. I already am working on that. Thanks.

**Comment by tznind** [comment]
Ah you are working on it. I did it in 3b6d6fce1d9c59c31eff2e2f31b5766bb987d5c6 and got the text view implementation down to just the below.  Sorry if we are duplicating work... Do you want to keep my implementation or I can revert it if you have something better.

```csharp
/// <summary>
	/// Renders an overlay on another view at a given point that allows selecting
	/// from a range of 'autocomplete' options.
	/// An implementation on a TextView.
	/// </summary>
	public class TextViewAutocomplete : Autocomplete {

		/// <inheritdoc/>
		protected override bool InsertSelection (View hostView, string accepted)
		{
			TextView host = (TextView)hostView;

			var typedSoFar = GetCurrentWord (host) ?? "";

			if (typedSoFar.Length < accepted.Length) {

				// delete the text
				for (int i = 0; i < typedSoFar.Length; i++) {
					host.DeleteTextBackwards ();
				}

				host.InsertText (accepted);
				return true;
			}

			return false;
		}

		/// <inheritdoc/>
		protected override string GetCurrentWord (View hostControl)
		{
			TextView host = (TextView)hostControl;

			var currentLine = host.GetCurrentLine ();
			var cursorPosition = Math.Min (host.CurrentColumn, currentLine.Count);
			return IdxToWord (currentLine, cursorPosition);
		}
	}
```

**Comment by BDisp** [comment]
> Sorry if we are duplicating work... Do you want to keep my implementation or I can revert it if you have something better.

No need to apologize. This way we share ideas. I think it's possible to simplify it even more and allowing other views to may po-pup suggestions even if they don't have the necessary size to show it.

**Pull request merged**
