### PR TITLE
Implementing HistoryText class and more.

### PR DESCRIPTION
**Pull request by BDisp**
@tznind do you see the need renaming the `Autocomplete` virtual method `DeleteTextBackwards` to `DeleteCharLeft`?

### CODE REVIEW

**Comment by tznind** [comment]
Is this a refactoring or a new feature? should it be its own PR rather than part of keybindings PR? Might make it easier to review?

**Comment by BDisp** [comment]
Is a refactoring with new feature based on the keybindings. I can wait for it to be merged an create a new PR or you can merge and including it alluding in the description. What do you think?

**Comment by BDisp** [comment]
@tznind, given @tig already having merged your pr will be better I submit a new pr my self?

**Comment by tznind** [comment]
> @tznind, given @tig already having merged your pr will be better I submit a new pr my self?

Yes please, I think that makes sense and will be easiest.

**Pull request closed without merging**
