### PR TITLE
Allowing Autocomplete to popup inside or outside the container.

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by tznind** [comment]
Awesome thanks.  Shall I mark keybinding as ready for review do you think or is there more we need?

**Comment by BDisp** [comment]
Yes you can. I thought to add the change inside the container to false if not multine, but I do later.

**Comment by BDisp** [comment]
Thanks. I forgot to delete the `protected abstract Point GetCursorPosition ();` method. Before I had also created `protected abstract Point SetCursorPosition (Point curPos);`, but as I did not need them I only removed the `SetCursorPosition` and forgot to remove the `GetCursorPosition`. So my question is if I should remove the `GetCursorPosition` too, or I also should adding the `SetCursorPosition` for a possible future use. Then both or none.

**Comment by tznind** [comment]
Thanks for the heads up.  I've removed it in cf446f6b9614ad94840a39393372cfe1860fdc1b I think that if we don't need the method then reducing the overhead of implementing the abstract is worth removing it.

**Comment by BDisp** [comment]
I have doubts whether it is necessary to use an `interface` if an `abstract` class is provided because the last one already imposes its signature. Is it not duplicate work? Can you clarify please? Thanks.
If I need to contact you privately, how can I do it? If you agree, of course.

**Comment by tznind** [comment]
Well interfaces are normally nice because they allow [Mocking in tests](https://circleci.com/blog/how-to-test-software-part-i-mocking-stubbing-and-contract-testing/) more easily than an abstract.  Also they normally help distinguish the public 'minimum requirements for an implementation of IAutocomplete` from the implementation detail of the abstract base class.

Normally I would say that if it doesn't hurt then just leave it.  That said we don't have an `IView` etc so if you think it is better to remove it I wouldn't mind.

I think we could remove from the interface things that are not likely to be called other than by the `Autocomplete` base class and therefore are not strictly required when implementing `IAutocomplete`:

- `void EnsureSelectedIdxIsValid ();`
- `bool IsWordChar (Rune rune);`
- `void ClearSuggestions ();`
- `int SelectedIdx { get; set; }`
- `int ScrollOffset { get; set; }`

What do you think?

**Comment by BDisp** [comment]
Ah thank you. This already makes much more sense. I agree with you, but in this case the `Autocomplete` statement in `TextView` and `TextField` should be changed to `IAutocomplete` and add to the interface the methods that are still missing. Right?

**Comment by tznind** [comment]
I think it is more about removing methods from `IAutocomplete`.  

- `IAutocomplete` should only have methods that are needed to be called from `TextView` or `TextField` or is helpful for API users
- `Autocomplete` can stay as it is

So for example `MaxWidth` is good in the interface because API users might want to adjust that on a given instance of `TextView`.  But  `void EnsureSelectedIdxIsValid ();` is very implementation specific and not something the API user would normally be calling.  Therefore it shouldn't be in the interface `IAutocomplete`.

I can update it to remove those methods if you want so you can see what I mean?

**Comment by BDisp** [comment]
> I can update it to remove those methods if you want so you can see what I mean?

Please do it. The interface must only have declarations of what the user need to call from the class that has declared an `IAutocomplete`.

> That is already how it is:
> 
> ```cs
> public IAutocomplete Autocomplete { get; protected set; } = new TextFieldAutocomplete ();
> ```

Sorry I thought it was as `public Autocomplete Autocomplete { get; protected set; } = new TextViewAutocomplete ();`

**Pull request merged**
